### ISSUE TITLE
build.sh -> glibc/glibc-common dependency issue

### ISSUE THREAD

**Issue by aff** [tomharvey/glpk-lambda-layer#1]
Hi and thanks for making glpk-lambda-layer public. I run into a dependency issue when running build.sh: 
```
Error: Package: glibc-2.17-196.172.amzn1.i686 (amzn-updates)
           Requires: glibc-common = 2.17-196.172.amzn1
           Installed: glibc-common-2.17-260.175.amzn1.x86_64 (@amzn-updates/latest)
               glibc-common = 2.17-260.175.amzn1
           Available: glibc-common-2.17-157.169.amzn1.x86_64 (amzn-main)
               glibc-common = 2.17-157.169.amzn1
           Available: glibc-common-2.17-157.170.amzn1.x86_64 (amzn-updates)
               glibc-common = 2.17-157.170.amzn1
           Available: glibc-common-2.17-196.172.amzn1.x86_64 (amzn-updates)
               glibc-common = 2.17-196.172.amzn1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

```
I am completely new to Docker. Thanks for any helpful hints.

**Comment by tomharvey** [comment]
Looks like the version of glibc on the image is ahead of the version required. I'll have a look tonight and post a fix.

**Comment by tomharvey** [comment]
Thanks @aff for digging this up - I've set the yum installation of `rpmdevtools` to not worry so much about the duplicate glibc installations.

Also - i've upgraded to a newer point version of glpk - `4.65-2.2` 

Should run now OK.

**Comment by tomharvey** [comment]
If it doesn't work, let me know. Otherwise I'll close the issue.

Also - if it doesn't; here is the zip, ready to be published as a layer. Hopefully this gets you working while any outstanding issues linger. Just put it in the same folder as this git repo and use the `./publish.sh` command to get it live in your AWS account.

[layer.zip](https://github.com/tempusenergy/glpk-lambda-layer/files/3125290/layer.zip)

**Comment by tomharvey** [comment]
I'll also start to add .zip files ready to publish in the [releases page of this repo](https://github.com/tempusenergy/glpk-lambda-layer/releases/) for those who can't/won't use docker and who explicitly trust my compilation :)

Big thanks for calling out the error. Hope you get some good use of the layer!

**Comment by aff** [comment]
Hi Tom, thanks for quick response and great help. Layer is created. Please close. Thanks.

**Comment by tomharvey** [comment]
Glad you’re getting some use from it. It’s a fairly niche cross section of linear and lambda.
